// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9k_naoKpD9cHSILbzjtMJRmWIQaTEUbU',
    appId: '1:921397206784:web:73b0963f86b00c84cc1de5',
    messagingSenderId: '921397206784',
    projectId: 'businesschat-c3a79',
    authDomain: 'businesschat-c3a79.firebaseapp.com',
    storageBucket: 'businesschat-c3a79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Rs3wfJv8AaMpaB7y0tGe67LfO9f6h2U',
    appId: '1:921397206784:android:0e7a3df426ab982fcc1de5',
    messagingSenderId: '921397206784',
    projectId: 'businesschat-c3a79',
    storageBucket: 'businesschat-c3a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8gEsAK14PPO_kgwp8_0i4XYlnLuNInbI',
    appId: '1:921397206784:ios:04a0e12a53958c16cc1de5',
    messagingSenderId: '921397206784',
    projectId: 'businesschat-c3a79',
    storageBucket: 'businesschat-c3a79.appspot.com',
    iosBundleId: 'com.example.businessChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8gEsAK14PPO_kgwp8_0i4XYlnLuNInbI',
    appId: '1:921397206784:ios:21c4528c0d3f879acc1de5',
    messagingSenderId: '921397206784',
    projectId: 'businesschat-c3a79',
    storageBucket: 'businesschat-c3a79.appspot.com',
    iosBundleId: 'com.example.businessChat.RunnerTests',
  );
}
